import Head from 'next/head'

import Header from '@/components/Header'
import Banner from '@/components/Banner'
import Features from '@/components/Features'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-hidden">
        <Header />
        <Banner />
        <Features />
        <Footer />
      </main>
    </>
  )
}
