import Head from 'next/head'

import Header from '@/components/Header'
import IntroBanner from '@/components/IntroBanner'
import IntroAnimate from '@/components/IntroAnimate'
import GameModes from '@/components/GameModes'
import Heroes from '@/components/Heroes'
import News from '@/components/News'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="snap relative h-screen w-full snap-y snap-mandatory overflow-auto scroll-smooth">
        <Header />
        <IntroBanner />
        <IntroAnimate />
        <GameModes />
        <Heroes />
        <News />
        <Footer />
      </main>
    </>
  )
}
